type Deposit {
  id: String!
  commitment: String!
  leaf_index: Int!
  timestamp: BigInt!
  block_number: Int!
  tx_hash: String!
}

type Withdrawal {
  id: String!
  recipient: String!
  nullifier_hash: String!
  block_number: Int!
  tx_hash: String!
}

type WbtcOrder {
  id: String!
  wbtc_seller: String!
  alice_strk_destination: String!
  wbtc_amount: String!
  quoted_strk_amount: String!
  hashlock: String!
  expiry: BigInt!
  rate_expiry: BigInt!
  wbtc_buyer: String
  strk_order_id: String
  strk_amount_locked: String
  bob_expiry: BigInt
  is_filled: Boolean!
  is_withdrawn: Boolean!
  is_refunded: Boolean!
  posted_at_block: Int!
  posted_tx_hash: String!
  filled_at_block: Int
  withdrawn_at_block: Int
  refunded_at_block: Int
}

type StrkOrder {
  id: String!
  strk_seller: String!
  strk_buyer: String!
  strk_amount: String!
  hashlock: String!
  expiry: BigInt!
  wbtc_order_id: String
  is_withdrawn: Boolean!
  is_refunded: Boolean!
  posted_at_block: Int!
  posted_tx_hash: String!
  withdrawn_at_block: Int
  refunded_at_block: Int
}

type OwnershipTransfer {
  id: String!
  previous_owner: String!
  new_owner: String!
  block_number: Int!
  tx_hash: String!
}
